name: Package repository
on: 
  pull_request:
    branches:
      - main
      - dev
      - 'feature/**'
jobs:
  Package-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.10
        with:
          versionSpec: '5.x'
          
      - name: Identify base branch
        run: |
          echo dst branch ${{github.base_ref}}    
          echo ${{github.event_name}}
          echo ${{github.ref_name}}
          echo src branch ${{github.head_ref}}
          
      - name: Run tests
        run: |
          echo tests!!
          
          
      - name: Build the repo
        run: |
          echo build!!!
     
          
#       - name: Determine Version
#         id: gitversion
#         uses: gittools/actions/gitversion/execute@v0.9.10
          
          
#       - name: Tag the repo
#         run: |
#           echo "tag ${{ steps.gitversion.outputs.fullSemVer }}"
      
      - name: Update commit comment
        run: |
          echo ${{ github.event }}
# github.repos.updateCommitComment({
#             owner: context.repo.owner,
#             repo: context.repo.repo,
#           })
                    
          
#       - name: Create tag
#         uses: actions/github-script@v3
#         with:
#           github-token: ${{ github.token }}
#           script: |
#             github.git.createRef({
#               owner: context.repo.owner,
#               repo: context.repo.repo,
#               ref: "refs/tags/${{ steps.gitversion.outputs.fullSemVer }}",
#               sha: context.sha
#             })

          
      - name: Publish
        run: |
          echo Publish!!!
          
      
        
#       - name: Display GitVersion outputs
#         run: |
#           echo "Major: ${{ steps.gitversion.outputs.major }}"
#           echo "Minor: ${{ steps.gitversion.outputs.minor }}"
#           echo "Patch: ${{ steps.gitversion.outputs.patch }}"
#           echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"
#           echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"
#           echo "BranchName: ${{ steps.gitversion.outputs.branchName }}"
#           echo "CommitDate: ${{ steps.gitversion.outputs.commitDate }}"
#       - name: Package Source
#         run: |
#           tar -czvf source.${{ steps.gitversion.outputs.fullSemVer }}.tar.gz ./*
