name: Package repository
on: 
  push:
    branches:
      - main
      - dev
      - 'feature/**'
jobs:
  Package-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.10
        with:
          versionSpec: '5.x'
          
      - name: Identify base branch
        run: |
          echo ${{github.base_ref}}
          echo ${{github.event_name}}
          echo ${{github.ref_name}}
          
#       - name: Determine Version
#         id: gitversion
#         uses: gittools/actions/gitversion/execute@v0.9.10
        
#       - name: Display GitVersion outputs
#         run: |
#           echo "Major: ${{ steps.gitversion.outputs.major }}"
#           echo "Minor: ${{ steps.gitversion.outputs.minor }}"
#           echo "Patch: ${{ steps.gitversion.outputs.patch }}"
#           echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"
#           echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"
#           echo "BranchName: ${{ steps.gitversion.outputs.branchName }}"
#           echo "CommitDate: ${{ steps.gitversion.outputs.commitDate }}"
#       - name: Package Source
#         run: |
#           tar -czvf source.${{ steps.gitversion.outputs.fullSemVer }}.tar.gz ./*
