name: Update Semver by Branchname
on: 
  issue_comment:
    types: [created]
    branches:
      - main
      - dev
      - 'feature/**'
jobs:
  Package-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Display names
        run: echo ${{ github.head_ref }} "->" ${{ github.base_ref }}
        
      - name: Execute for pull request comments only
        if: github.event.issue.pull_request
        run: echo "This is a pull request comment event"
      
      - name: Merge feature to dev
        run: |
          if [[ ${{github.head_ref}} =~ feature\/.* && ${{github.base_ref}} == dev ]]; then
            echo "Merging ${{github.head.ref}} to dev"
            echo ${{ github.event.commits }}
            echo ${{ github.event.commits[0].message }}
            echo ${{ toJSON(github.event.commits) }}
            echo ${{ toJSON(github.event ) }}
          else
            exit 1
          fi
          
          
        
